apiVersion: v1
kind: ConfigMap
metadata:
  name: build-tools
data:
  Dockerfile: |
    FROM node:16-alpine3.12

    # Create app directory
    WORKDIR /usr/src/app

    # Install app dependencies
    COPY package*.json ./

    RUN npm install

    # Copy source code
    COPY . .

    EXPOSE 8080
    CMD [ "node", "server.js" ]

  package.json: |
    {
      "name": "my_nodejs_app",
      "version": "1.0.0",
      "description": "Node.js App",
      "author": "Romain Boulanger",
      "main": "server.js",
      "scripts": {
        "start": "node server.js"
      },
      "dependencies": {
        "express": "^4.17.1"
      }
    }

  server.js: |
    'use strict';

    const express = require('express');

    // Define host and port
    const PORT = 8080;
    const HOST = '0.0.0.0';

    // App
    const app = express();
    app.get('/', (req, res) => {
      res.send('Hello Kubernetes !');
    });

    app.listen(PORT, HOST);

