apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robot
subjects:
# You can specify more than one "subject"
- kind: User
  name: system:serviceaccount:default:robot
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: robot # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

