
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: reg.ntl.nc/library/nginx:latest
    name: nginx
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: robot
  serviceAccountName: robot
  volumes:
  - name: robot
    projected:
      sources:
      - serviceAccountToken:
          path: robot
          expirationSeconds: 7200
