apiVersion: v1
kind: Pod
metadata:
  name: secret-mount
spec:
  containers:
  - name: mypod
    image: reg.ntl.nc/library/alpine:latest
    command: ["sleep", "3600"]
    volumeMounts:
    - name: user-pass
      mountPath: "/tmp/db-user-pass"
      readOnly: true
  volumes:
  - name: user-pass
    secret:
      secretName: db-user-pass

