# Write the netpolicy here.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-demoapp-to-redis
  namespace: demoapp
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: demoapp
      ports:
        - protocol: TCP
          port: 6379
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-nginx-to-demoapp
  namespace: demoapp
spec:
  endpointSelector:
    matchLabels:
      app: demoapp
  ingress:
    # 1) Autorise les pods ingress-nginx (namespace -> pods)
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: ingress-nginx
            k8s:app.kubernetes.io/name: ingress-nginx
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP
    # 2) Autorise le trafic venant du host (ingress en hostNetwork/hostPort)
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP


